// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhalesExchangeBackend.Data;

#nullable disable

namespace WhalesExchangeBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421103122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WhalesExchangeBackend.SharedLib.Data.DbSwap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountToPaySats")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToReceiveSats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTxData")
                        .HasMaxLength(8388608)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FailTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontendId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FundingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundingTxData")
                        .HasMaxLength(8388608)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundingTxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockupAddress")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LockupOutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderPubkey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpentTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeoutBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrontendId");

                    b.HasIndex("IsForward");

                    b.HasIndex("ProviderPubkey");

                    b.HasIndex("Status");

                    b.ToTable("DbSwap");
                });

            modelBuilder.Entity("WhalesExchangeBackend.SharedLib.Data.DbSwapProvider", b =>
                {
                    b.Property<string>("Pubkey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxAmountForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxAmountReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinAmountForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinAmountReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MiningFeeForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MiningFeeReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentageFeeForward")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageFeeReverse")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoWBits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsMissed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsPresent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pubkey");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Pubkey");

                    b.ToTable("DbSwapProvider");
                });

            modelBuilder.Entity("WhalesExchangeBackend.SharedLib.Data.DbSwap", b =>
                {
                    b.HasOne("WhalesExchangeBackend.SharedLib.Data.DbSwapProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderPubkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
