// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhalesExchangeBackend.Data;

#nullable disable

namespace WhalesExchangeBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326160301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WhalesExchangeBackend.Data.DbSwapProvider", b =>
                {
                    b.Property<string>("Pubkey")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxAmountForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxAmountReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinAmountForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinAmountReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MiningFeeForwardSat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MiningFeeReverseSat")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentageFeeForward")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageFeeReverse")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoWBits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pubkey");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Pubkey");

                    b.ToTable("DbSwapProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
